package common

object AppConstants {
  val MAX_EMPLOYEE_COUNT = 6

  val MIN_EMPLOYEE_AGE = 21

  val DIRECTOR_QUALIFICATION_AGE = 40

  val BOARD_OF_DIRECTORS = "BOD"

  val ENGINEERING_DEPARTMENT  = "ENG"

  val OPERATIONS_DEPARTMENT = "OPR"

  val SERVICE_DEPARTMENT = "SER"
}
